import { Montserrat } from 'next/font/google'
import type { Metadata } from 'next'
import './globals.css'

import { Footer } from '@/components/footer/footer'

const inter = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PADC LLC',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="app_wrapper">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
